# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: docker build -t alpine-fastpack linux-build/alpine
    displayName: 'docker build'
  - script: docker run --rm alpine-fastpack "/bin/bash -c 'make fetch install && make setup-test && make test && make test-integration'"
    displayName: 'make test'
